/* autogenerated from messages.mc */

#include <nms_common.h>

#include <unicode.h>

const TCHAR *g_szMessages[] = {
	_T(""),
	_T("NetXMS Client Proxy started"),
	_T("NetXMS Client Proxy stopped"),
	_T("Unable to open socket: %1"),
	_T("Unable to bind socket: %1"),
	_T("Unable to accept incoming connection: %1"),
	_T("Too many consecutive errors on accept() call"),
	_T("WSAStartup failed: %1"),
	_T("%1"),
	_T("Signal %1 received"),
	_T("Failed to initialize cryptografy module"),
	_T("Listening on socket %1:%2"),
	_T("EXCEPTION %1 (%2) at %3 (crash dump was generated); please send files %4 and %5 to dump@netxms.org"),
	_T("Debug level set to %1"),
	_T("Call to select() failed: %1")
};

unsigned int g_dwNumMessages = 15;
